development:
  adapter: sqlite3
  database: database.db

test:
  adapter: sqlite3
  database: database.db

production:
  adapter: postgresql
  database: baby_steps_database #rename this to whatever you want
  username: username
  password: password
  host: localhost
